### ISSUE TITLE
Task 3: Undefined variable "reviews_split" 

### ISSUE THREAD

**Issue by sharadkak** [kumar-shridhar/Very-Deep-Learning-NLP#1]
In VeryDeepLearningNLP notebook, in Task 3, an undefined variable "reviews_split" is being called, I am not sure if we are supposed to define the variable as there are no instructions given.

**Comment by kumar-shridhar** [comment]
Hi Sharad, 
Thanks for pointing this out. I updated the notebook. Please have a look.

**Comment by sharadkak** [comment]
Yeah I had a look, thanks for fixing it :)
